### ISSUE TITLE
Globs and other issues

### ISSUE THREAD

**Issue by gpbl** [keithamus/hashmark#1]
Hi, thanks for this module, I'm trying it but I can't get it working :(

I pass a glob like this: 
```
./node_modules/hashmark/bin/hashmark -l 8 build/public/**/* {dir}/{name}.{hash}.{ext}
```
but it outputs only the first matched file. 

Other questions:
* The README refers to a `bashmark`, but i can't find it in the `/bin` dir. Is that just a typo?
* How do you change the assets path in your css files?
* Is it possible to *not* rename the file and produce only the assets json? on my web server i use a rewrite to serve hashed filenames

Thanks :+1:

**Comment by withdust** [comment]
wrap the path that contains the glob in quotes ? ...  `'build/public/**/*'`

otherwise the shell seems to be globbing the path into an array before it gets to `bin/hashmark` and then when hashmark tries to expand it with `files = cli.glob.sync(cli.args[0]);`, `cli.args[0]`  is actually the first filename in the array rather than the original path with wildcards.

**Comment by keithamus** [comment]
@withdust that seems like a bug too. I think it should probably consume all of cli.args - as the remaining args should all be file references. Probably a throwback from an early version when it only accepted 1 file .

**Comment by withdust** [comment]
@keithamus so no need to use cli.glob then ?

**Comment by keithamus** [comment]
Still a need to use cli.glob, as Windows users will need the support. More a case that cli.glob needs to be passed the whole cli.args array.

**Comment by sunshineo** [comment]
Would someone fix this soon? The tool is not very useful when it cannot handle blob. Also one more thing I'd like to report: the tool does not try to create the folder and fails even for a single file when the target folder does not exists.

I read http://blog.keithcirkel.co.uk/how-to-use-npm-as-a-build-tool/ and then try to switch from grunt to pure npm. @keithamus , do you feel grunt / gulp actually have some value?

**Comment by lydell** [comment]
Hopefully I'll get the time to fix this tonight.

**Comment by michaeljwilliams** [comment]
@withdust @keithamus I can confirm that the quotes around the paths are completely necessary. Without them hashmark does weird things. With them, recursive globby goodness works just fine.

I used the following command to get hashmark to hash all files in the current directory and all files in all subdirectories with the extension '.txt', with the hash shortened to 4 characters. `hashmark -l 4 '**/*.txt' '{dir}/{name}.{hash}.{ext}'`

The `'{dir}/{name}.{hash}.{ext}'` puts each hashed file back where it was found, and names the hashed file like 'example.1h56.txt'.

**Comment by lydell** [comment]
Since I never got around fixing it, I'm glad to see there's a workaround.

**Comment by michaeljwilliams** [comment]
@lydell Is it really a workaround though? In my mind it seems like proper usage would entail always putting that arg in quotes. The destination arg already is, why not source?

**Comment by lydell** [comment]
> Is it really a workaround though?

Yes, it is a workaround. 

> In my mind it seems like proper usage would entail always putting that arg in quotes.

No, that's not proper. No other CLI programs requires quoting.

> The destination arg already is, why not source?

The destination arg does _not_ need quoting. (It might help, though, if your shell requires escaping otherwise.)

> When not using quotes for the source, and using a glob, you let the shell do some work in passing the files to hashmark.

Exactly. That's the point.

> Without quotes around the source, the full arg is never passed to hashmark, so cli and glob cannot help you. Am I right?

Yes, that's the point. hashmark should not have to think about globs at all, because that's a shell feature. However, just like a few other CLI programs, hashmark has decided to include glob expansion for Windows users (Windows' default shell hasn't got glob support).

**Comment by lydell** [comment]
I didn't have the time to test it, but changing https://github.com/keithamus/hashmark/blob/master/bin/hashmark#L52-L54 into something like the following might do the trick.

```js
if (cli.args.length) {
    if (process.platform === 'win32' && !process.env.TERM) {
        files = cli.args.reduce(function(files, pattern) {
            return files.concat(cli.glob.sync(pattern));
        }, []);
    } else {
        files = cli.args;
    }
}
```

**Comment by keithamus** [comment]
Most of this boils down to the fact that the CLI only takes 1 file argument [bin/hashmark#L53](https://github.com/keithamus/hashmark/blob/master/bin/hashmark#L53), which is a bug.

While glob exists for Windows compatibility, IMO there is no need to detect the platform and perform the globbing only if the platform is windows, as Bash et al do not always have the advanced globbing features that `npm-glob` has.

Just replacing L53 with the following will fix this issue:

```js
        files = cli.args.reduce(function(files, pattern) {
            return files.concat(cli.glob.sync(pattern));
        }, []);
```

Anyone who has commented here is encouraged to make a PR to that effect, and back it up with a few tests. They will be rewarded a million internet points, and a commemorative plaque on our heroes page: https://github.com/keithamus/hashmark/graphs/contributors.

**Comment by lydell** [comment]
No unix shell user would ever expect globs to work in a specific program but not in the rest of the shell. Besides, `foo \*.js` should hash a file named `*.js`, not all .js files in the current directory. So IMO the platform check is needed.

**Comment by keithamus** [comment]
You make a good point. Feel free to make a pr for the code sample you suggested that includes the platform check then.

**Comment by lydell** [comment]
Sure, I could make a PR. The problem is that I don't have a Windows machine to test on. It would be great if somebody could run `node -p 'process.platform === "win32" && !process.env.TERM'` on Windows. That should print 'false' in cmd.exe and in PowerShell, but 'true' in MinGW ("Git bash") and cygwin.

**Comment by michaeljwilliams** [comment]
> Yes, that's the point. hashmark should not have to think about globs at all, because that's a shell feature. However, just like a few other CLI programs, hashmark has decided to include glob expansion for Windows users (Windows' default shell hasn't got glob support).

Yes, hashmark mark does indeed need to think about globs, because recursive globbing is *not* a shell feature for many (most?) Unix users. Only bash > 4 supports recursive globs. I and many others have an older version of bash than 4 on my system and cannot do recursive globs in the shell. 

> No unix shell user would ever expect globs to work in a specific program but not in the rest of the shell.

This is exactly what I expect.

> While glob exists for Windows compatibility, IMO there is no need to detect the platform and perform the globbing only if the platform is windows, as Bash et al do not always have the advanced globbing features that npm-glob has.

Keith is right, and this is why he chose to include npm-glob in the module.

**Comment by keithamus** [comment]
Some equally good points there too.

To look at some examples of other projects - e.g. [tape](https://github.com/substack/tape/blob/master/bin/tape), they use `glob()` without doing platform detection - so I think it is a reasonable thing to do.

Let's just do the simplest thing - globbing without platform detection. If real issues arise from doing this, then we can look at fixing those or worst case reverting the change.

**Comment by lydell** [comment]
Nice to see that we've settled on something. Unix users escaping globs to pass in weirdly named files sure is an edge case.

**Comment by keithamus** [comment]
Worst case scenario, we can turn off argument globbing after a `--` right? so if users need to pass weird filenames they can do something like `hashmark *.js -- \*.js`

**Comment by lydell** [comment]
Yeah, that could be a way to go. But let's do like you said and not worry about it until real issue arise.

**Comment by michaeljwilliams** [comment]
@keithamus I tested the new L53 code
> files = cli.args.reduce(function(files, pattern) {
            return files.concat(cli.glob.sync(pattern));
        }, []);

Results are that hashmark can accept more than one specified file, with or without quotes, but double glob source still only works *with* quotes. Double glob destination works fine without quotes.

**Comment by keithamus** [comment]
@michaeljwilliams sounds like a limitation of your shell. Not sure how we can avoid that problem. Suggestions welcome.

**Comment by lydell** [comment]
This is a good debugging script:

```js
console.dir(process.argv)
```

Then run `node testfile.js arg1 **/*.js arg3` etc.

**Comment by michaeljwilliams** [comment]
@keithamus >sounds like a limitation of your shell. Not sure how we can avoid that problem. Suggestions welcome.

I really have no idea, but I think we ought to at least put the workaround in the documentation, if not fix it, because I'm using the same Bash that shipped with my MacBook Pro, and I imagine tons of developers use MacBook Pros.

**Comment by keithamus** [comment]
Sounds like quoting it is going to have to be a thing. As I think bash will pick up any glob syntax before it hits the cli app. This should be well documented in the readme, as you suggest.

**Comment by lydell** [comment]
But first we should try things out, not just guess. Try my test script (or `echo`) to see what the JS actually gets. I can try out bash and sh on Ubuntu.

**Comment by lydell** [comment]
Seems like both bash and sh have `**` enabled by default on my machine -.-

**Comment by keithamus** [comment]
It is more of an educated guess than you might believe. You've likely got the `globstar` shell option switched on. If you run `shopt | grep globstar` you'll likely see `globstar on`. With `globstar` set to on, doing `**` will expand through folders, while off it'll behave like `*`. 

See this article for more: http://www.linuxjournal.com/content/globstar-new-bash-globbing-option

Summary: without quotes, bash will swallow all glob control characters, and may or may not use them as implied by their feature.

**Comment by michaeljwilliams** [comment]
@keithamus @lydell Here's the official explanation for why the quotes are needed. From the Bash manual:
> 3.1.2.2 Single Quotes
>
> Enclosing characters in single quotes (‘'’) preserves the literal value of each character within the quotes. A single quote may not occur between single quotes, even when preceded by a backslash.

Using the quotes passes the asterisks as actual asterisks, and they get handled by the glob module.

**Comment by keithamus** [comment]
Thanks @michaeljwilliams :smile:

**Comment by lydell** [comment]
If a glob doesn’t match anything, bash sends the glob expression through unmodified. For example, `echo *.js` will print a list of all .js files, unless there are none; then `*.js` is printed. This led me to believe that `echo **` would print `**` if you turn of `shopt -u globstar`. However, that seems to have the same effect as `echo *`. Why? I finally figured it out. `echo *a*` prints a list of all files containing an 'a'. In other words, files which start with anything, then has an 'a' and then ends with anything are matched. `echo **` works the same way: Files which start with anything, then has an empty string an then ends with anything are matched (which in effect is equivalent to `echo *`).

I also seem to have missed the point of adding JS-powered glob support. I thought it was to make things more convenient for Windows users, but in fact the most important point is writing cross-platform npm scripts.

I suggest the following:

- Skip the platform check.
- Windows users can use glob patterns without quoting.
- Most unix users can use glob patterns without quoting too, since unix shells usually support globs out of the box.
- If your unix shell does not support `**` but does support `*` and you want to use the JS-powered `**`, you’re best off quoting.
- If you want to write a really robust npm script, quote the glob patterns.
